### PR TITLE
Upgrade OpenAPI spec for synthetics to match production api servers

### PR DESCRIPTION
**Pull request by mateuszmidor**

### CODE REVIEW

**Review by Fenthick — APPROVED** [review]
Maybe it's time to update generate_client.sh to download schema from api-schema-public?

**Comment by mateuszmidor** [comment]
> Maybe it's time to update generate_client.sh to download schema from api-schema-public?

You need to establish some way of communication from Kentik engineers to update the repo once they move/remove/change format of the spec.
And you need an automatic converter Swagger2->OpenAPI3 for that.
We can can give it a try when done with higher priority things from backlog.

**Comment by Fenthick** [comment]
> > Maybe it's time to update generate_client.sh to download schema from api-schema-public?
> 
> You need to establish some way of communication from Kentik engineers to update the repo once they move/remove/change format of the spec.
> And you need an automatic converter Swagger2->OpenAPI3 for that.
> We can can give it a try when done with higher priority things from backlog.

1. I suppose that content of the schema changes more often than its location/format, so IMO it's still better to try downloading latest schema (it would almost never fail). And generating client based on stale schema will cause the app to fail more often.

2. Openapi-generator supports OpenAPI v2 input - I tried it in Go APIv6 client. So in fact there is no need to convert schema to v3. However, it should be double-checked

After rethinking:
Eventually we should use client from community_sdk_python (which would probably import generated code from api-schema-public) and then resolve those problems. I can think of
- removing cached schemas to prevent build client from stale schema (discussed above)
- running nightly builds on all repos to catch problems early
- implementing real-api acceptance tests in community-sdk-golang and sla web-app 
- setting up CI of api-schema-public to trigger jobs in community-sdk-golang and sla web-app (that could be "non-voting" job), so that we have immediate information that downstream  repos are broken

**Comment by mmac-m3a** [comment]
> > > Maybe it's time to update generate_client.sh to download schema from api-schema-public?
> > 
> > 
> > You need to establish some way of communication from Kentik engineers to update the repo once they move/remove/change format of the spec.
> > And you need an automatic converter Swagger2->OpenAPI3 for that.
> > We can can give it a try when done with higher priority things from backlog.
> 
>     1. I suppose that content of the schema changes more often than its location/format, so IMO it's still better to try downloading latest schema (it would almost never fail). And generating client based on stale schema will cause the app to fail more often.
> 
>     2. Openapi-generator supports OpenAPI v2 input - I tried it in Go APIv6 client. So in fact there is no need to convert schema to v3. However, it should be double-checked
> 
> 
> After rethinking:
> Eventually we should use client from community_sdk_python (which would probably import generated code from api-schema-public) and then resolve those problems. I can think of
> 
>     * removing cached schemas to prevent build client from stale schema (discussed above)
> 
>     * running nightly builds on all repos to catch problems early
> 
>     * implementing real-api acceptance tests in community-sdk-golang and sla web-app
> 
>     * setting up CI of api-schema-public to trigger jobs in community-sdk-golang and sla web-app (that could be "non-voting" job), so that we have immediate information that downstream  repos are broken

The SLA dashboard app definitely should use the `community-sdk-python`. Is there any reason not to. I though it did, but I've never checked.

**Comment by mmac-m3a** [comment]
> > > Maybe it's time to update generate_client.sh to download schema from api-schema-public?
> > 
> > 
> > You need to establish some way of communication from Kentik engineers to update the repo once they move/remove/change format of the spec.
> > And you need an automatic converter Swagger2->OpenAPI3 for that.
> > We can can give it a try when done with higher priority things from backlog.
> 
>     1. I suppose that content of the schema changes more often than its location/format, so IMO it's still better to try downloading latest schema (it would almost never fail). And generating client based on stale schema will cause the app to fail more often.
> 
>     2. Openapi-generator supports OpenAPI v2 input - I tried it in Go APIv6 client. So in fact there is no need to convert schema to v3. However, it should be double-checked
> 
> 
> After rethinking:
> Eventually we should use client from community_sdk_python (which would probably import generated code from api-schema-public) and then resolve those problems. I can think of
> 
>     * removing cached schemas to prevent build client from stale schema (discussed above)
> 
>     * running nightly builds on all repos to catch problems early
> 
>     * implementing real-api acceptance tests in community-sdk-golang and sla web-app
> 
>     * setting up CI of api-schema-public to trigger jobs in community-sdk-golang and sla web-app (that could be "non-voting" job), so that we have immediate information that downstream  repos are broken

I 100% agree! Also, one we migrate SDKs to use to use gRPC for all v6 APIs, majority of compatibility problems should go away. Eventually, v6 will support all API functionality, so we should optimize for this case.

**Pull request closed without merging**
